from __future__ import annotations

import json
from pathlib import Path

from .business_units import (
    BusinessUnitBlueprint,
    BusinessUnitWorker,
    TeamBlueprint,
)


def _worker(
    worker_id: str,
    name: str,
    role_name: str,
    team_id: str,
    reports_to: str | None,
    *capabilities: str,
) -> BusinessUnitWorker:
    return BusinessUnitWorker(
        worker_id=worker_id,
        name=name,
        role_name=role_name,
        team_id=team_id,
        reports_to=reports_to,
        capabilities=frozenset(capabilities),
        authority_level="B",
        paid_ai_enabled=False,
        external_actions_enabled=False,
    )


def animation_studio_blueprint() -> BusinessUnitBlueprint:
    teams = (
        TeamBlueprint(
            "studio-management",
            "Studio Management",
            "studio-director-01",
            "Own production strategy, scheduling, quality, cost, and escalation.",
        ),
        TeamBlueprint(
            "story",
            "Story & Continuity",
            "studio-story-director-01",
            "Create age-appropriate episodic stories and preserve canon continuity.",
        ),
        TeamBlueprint(
            "art",
            "Art & Visual Development",
            "studio-art-director-01",
            "Preserve character identity, visual language, environments, and shot intent.",
        ),
        TeamBlueprint(
            "animation",
            "Animation & Post",
            "studio-animation-director-01",
            "Turn approved scene plans into consistent motion and final picture.",
        ),
        TeamBlueprint(
            "audio",
            "Voice, Music & Sound",
            "studio-voice-director-01",
            "Produce character-consistent dialogue, music, ambience, and effects.",
        ),
        TeamBlueprint(
            "localization",
            "Localization",
            "studio-localization-lead-01",
            "Adapt approved episodes across target languages while preserving meaning.",
        ),
        TeamBlueprint(
            "quality",
            "Quality & Safety",
            "studio-qa-lead-01",
            "Gate continuity, child-safety, technical integrity, and final release readiness.",
        ),
        TeamBlueprint(
            "publishing-growth",
            "Publishing & Growth",
            "studio-publishing-lead-01",
            "Prepare owner-approved metadata, packaging, analytics, and growth experiments.",
        ),
    )

    workers = (
        _worker(
            "studio-director-01",
            "Animation Studio Director",
            "studio_director",
            "studio-management",
            None,
            "studio_strategy",
            "production_planning",
            "resource_allocation",
            "cross_team_routing",
            "escalation",
        ),
        _worker(
            "studio-production-manager-01",
            "Production Manager",
            "production_manager",
            "studio-management",
            "studio-director-01",
            "scheduling",
            "episode_tracking",
            "dependency_management",
            "cost_tracking",
        ),
        _worker(
            "studio-story-director-01",
            "Story Director",
            "story_director",
            "story",
            "studio-director-01",
            "story_architecture",
            "episode_planning",
            "dialogue_review",
            "character_arc",
        ),
        _worker(
            "studio-writer-01",
            "Writer 01",
            "writer",
            "story",
            "studio-story-director-01",
            "screenwriting",
            "dialogue",
            "children_storytelling",
            "comedy",
        ),
        _worker(
            "studio-writer-02",
            "Writer 02",
            "writer",
            "story",
            "studio-story-director-01",
            "screenwriting",
            "dialogue",
            "educational_storytelling",
            "episode_variation",
        ),
        _worker(
            "studio-continuity-editor-01",
            "Character & Continuity Editor",
            "continuity_editor",
            "story",
            "studio-story-director-01",
            "character_bible",
            "canon_tracking",
            "continuity",
            "episode_memory",
        ),
        _worker(
            "studio-art-director-01",
            "Art Director",
            "art_director",
            "art",
            "studio-director-01",
            "visual_direction",
            "style_consistency",
            "character_review",
            "environment_review",
        ),
        _worker(
            "studio-character-designer-01",
            "Character Designer",
            "character_designer",
            "art",
            "studio-art-director-01",
            "character_design",
            "expression_sheet",
            "costume_consistency",
            "reference_assets",
        ),
        _worker(
            "studio-environment-artist-01",
            "Environment Artist",
            "environment_artist",
            "art",
            "studio-art-director-01",
            "background_design",
            "environment_design",
            "location_continuity",
            "color_script",
        ),
        _worker(
            "studio-storyboard-artist-01",
            "Storyboard & Shot Planner",
            "storyboard_artist",
            "art",
            "studio-art-director-01",
            "storyboard",
            "shot_planning",
            "camera_language",
            "scene_blocking",
        ),
        _worker(
            "studio-animation-director-01",
            "Animation Director",
            "animation_director",
            "animation",
            "studio-director-01",
            "animation_direction",
            "motion_consistency",
            "shot_approval",
            "render_planning",
        ),
        _worker(
            "studio-animation-engineer-01",
            "Animation Pipeline Engineer",
            "animation_pipeline_engineer",
            "animation",
            "studio-animation-director-01",
            "comfyui",
            "video_generation",
            "workflow_automation",
            "asset_pipeline",
        ),
        _worker(
            "studio-editor-compositor-01",
            "Editor & Compositor",
            "editor_compositor",
            "animation",
            "studio-animation-director-01",
            "editing",
            "compositing",
            "timing",
            "subtitle_burnin",
        ),
        _worker(
            "studio-voice-director-01",
            "Voice Director",
            "voice_director",
            "audio",
            "studio-director-01",
            "voice_casting",
            "age_gender_voice_design",
            "dynamic_guest_voice_casting",
            "animal_vocalization_casting",
            "character_voice_consistency",
            "dialogue_direction",
            "pronunciation",
        ),
        _worker(
            "studio-dubbing-engineer-01",
            "TTS & Dubbing Engineer",
            "dubbing_engineer",
            "audio",
            "studio-voice-director-01",
            "tts",
            "voice_synthesis",
            "voice_reference_generation",
            "multilingual_voice_cloning",
            "guest_voice_materialization",
            "lip_sync",
            "audio_cleanup",
        ),
        _worker(
            "studio-music-sfx-01",
            "Music & SFX Producer",
            "music_sfx_producer",
            "audio",
            "studio-voice-director-01",
            "music",
            "sound_effects",
            "mixing",
            "loudness",
        ),
        _worker(
            "studio-localization-lead-01",
            "Localization Lead",
            "localization_lead",
            "localization",
            "studio-director-01",
            "translation",
            "localization",
            "terminology_memory",
            "subtitle_adaptation",
        ),
        _worker(
            "studio-qa-lead-01",
            "Continuity, Quality & Child-Safety Lead",
            "quality_safety_lead",
            "quality",
            "studio-director-01",
            "qa",
            "continuity_qa",
            "child_safety",
            "technical_validation",
        ),
        _worker(
            "studio-publishing-lead-01",
            "Publishing & Metadata Specialist",
            "publishing_specialist",
            "publishing-growth",
            "studio-director-01",
            "metadata",
            "thumbnail_brief",
            "release_packaging",
            "channel_operations",
        ),
        _worker(
            "studio-analytics-growth-01",
            "Analytics & Growth Specialist",
            "analytics_growth_specialist",
            "publishing-growth",
            "studio-publishing-lead-01",
            "analytics",
            "retention_analysis",
            "experiment_design",
            "content_performance",
        ),
    )

    blueprint = BusinessUnitBlueprint(
        business_unit_id="animation-studio",
        name="AHOS Animation & Cartoon Studio",
        director_worker_id="studio-director-01",
        owner_controlled=True,
        teams=teams,
        workers=workers,
        owner_reserved_decisions=(
            "external publishing or messaging",
            "payments, purchases, or paid-provider activation",
            "contracts, customer commitments, or commercial offers",
            "credential or secret access",
            "destructive or irreversible actions",
            "new business-unit creation or closure",
            "material budget increases",
            "final release approval when owner gate is enabled",
        ),
    )
    return blueprint.validate()


def write_animation_studio_blueprint(path: str | Path) -> Path:
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(
            animation_studio_blueprint().to_dict(),
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )
    return destination